apiVersion: apps/v1
kind: Deployment
metadata:
  name: cruise-control
  namespace: myspace
spec:
  selector:
    matchLabels:
      app: cruise-control
  replicas: 1
  template:
    metadata:
      labels:
        app: cruise-control
      annotations:
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: init-config
        image: busybox@sha256:2a03a6059f21e150ae84b0973863609494aad70f0a80eaeb64bddd8d92465812
        command: ['/bin/sh']
        args: [ '-c', 'cp /etc/cruise-control-configmap/* /opt/cruise-control/config']
        volumeMounts:
        - name: configmap
          mountPath: /etc/cruise-control-configmap
        - name: config
          mountPath: /opt/cruise-control/config
      containers:
      - name: cruise-control
        image: solsson/kafka-cruise-control@sha256:f3f3775f3b5e2a5ae2da6fdae60ed118793ac32c80f13fba31be8f025a57f6ac
        imagePullPolicy: IfNotPresent
        ports:
        - name: api
          containerPort: 8090
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 8090
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /opt/cruise-control/config
      volumes:
      - name: configmap
        configMap:
          name: broker-cruise-control-config
      - name: config
        emptyDir: {}
