---
apiVersion: v1
kind: Service
metadata:
  name: pzoo
  namespace: myspace
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pzoo
  namespace: myspace
spec:
  template:
    spec:
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates: []
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zoo
  namespace: myspace
spec:
  template:
    spec:
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates: []
